### ISSUE TITLE
[BUG] Incorrect dependency specifiers for scipy

### ISSUE THREAD

**Issue by matrixji** [xprobe-inc/xorbits#196]
### Describe the bug
I install xorbits by pip, and try to import xorbits.pandas, which got below error:
```
Python 3.8.10 (default, Nov 14 2022, 12:59:47) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import xorbits.pandas as pd 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bji/.local/lib/python3.8/site-packages/xorbits/__init__.py", line 17, in <module>
    from .core import run
  File "/home/bji/.local/lib/python3.8/site-packages/xorbits/core/__init__.py", line 16, in <module>
    from .execution import run
  File "/home/bji/.local/lib/python3.8/site-packages/xorbits/core/execution.py", line 17, in <module>
    from .adapter import MarsEntity, mars_execute
  File "/home/bji/.local/lib/python3.8/site-packages/xorbits/core/adapter.py", line 26, in <module>
    from .._mars import dataframe as mars_dataframe
  File "/home/bji/.local/lib/python3.8/site-packages/xorbits/_mars/dataframe/__init__.py", line 17, in <module>
    from .initializer import DataFrame, Series, Index
  File "/home/bji/.local/lib/python3.8/site-packages/xorbits/_mars/dataframe/initializer.py", line 20, in <module>
    from ..tensor import tensor as astensor, stack
  File "/home/bji/.local/lib/python3.8/site-packages/xorbits/_mars/tensor/__init__.py", line 297, in <module>
    from . import special
  File "/home/bji/.local/lib/python3.8/site-packages/xorbits/_mars/tensor/special/__init__.py", line 18, in <module>
    from .err_fresnel import (
  File "/home/bji/.local/lib/python3.8/site-packages/xorbits/_mars/tensor/special/err_fresnel.py", line 221, in <module>
    @implement_scipy(spspecial.voigt_profile)
AttributeError: module 'scipy.special' has no attribute 'voigt_profile'
```

I've checked the installed packages in my python env. The root cause seems to: I've previously installed the `scipy==1.3.3`
After I manually update scipy to 1.4.1(Seems, for load xorbits.pandas at least needs 1.4.0), then it could work.

### To Reproduce
Could simply reproduce it by:
```
pip3 install 'scipy<1.4.0'
pip3 install xorbits
python3 -c 'import xorbits.pandas as pd'
```

### Additional context
I'd like to provide the PR to fix it, later.

**Comment by qianduoduo0904** [comment]
Nice catch, we are merging Mars (https://github.com/xprobe-inc/mars) into Xorbits via #195 , after that PR got merged, you can send a PR to fix this, thank you in advance, buddy.

**Comment by aresnow1** [comment]
For `voigt_profile`, we can check the scipy version before definition:
``` Python
if scipy.__version__ >= 1.4.0:
    @implement_scipy(spspecial.voigt_profile)
    @infer_dtype(spspecial.voigt_profile)
    def voigt_profile(x, sigma, gamma, **kwargs):
        op = TensorVoigtProfile(**kwargs)
        return op(x, sigma, gamma)
```
