### ISSUE TITLE
BUG: `read_parquet` requests much more memory than actual size

### ISSUE THREAD

**Issue by aresnow1** [xprobe-inc/xorbits#375]
### Describe the bug
When read parquet file, it raised a `ValueError` about memory.
```
2023-04-17 18:40:30,566 xorbits._mars.services.scheduling.worker.execution 6002 ERROR    Failed to run subtask 5FT8YxPGahqd1jWBN8drfcEn on band numa-0
Traceback (most recent call last):
  File "/home/fengyun/.local/lib/python3.8/site-packages/xorbits/_mars/services/scheduling/worker/execution.py", line 393, in internal_run_subtask
    subtask_info.result = await self._retry_run_subtask(
  File "/home/fengyun/.local/lib/python3.8/site-packages/xorbits/_mars/services/scheduling/worker/execution.py", line 494, in _retry_run_subtask
    return await _retry_run(subtask, subtask_info, _run_subtask_once)
  File "/home/fengyun/.local/lib/python3.8/site-packages/xorbits/_mars/services/scheduling/worker/execution.py", line 111, in _retry_run
    raise ex
  File "/home/fengyun/.local/lib/python3.8/site-packages/xorbits/_mars/services/scheduling/worker/execution.py", line 73, in _retry_run
    return await target_async_func(*args)
  File "/home/fengyun/.local/lib/python3.8/site-packages/xorbits/_mars/services/scheduling/worker/execution.py", line 423, in _run_subtask_once
    await quota_ref.request_batch_quota(batch_quota_req)
  File "xoscar/core.pyx", line 263, in __pyx_actor_method_wrapper
  File "xoscar/core.pyx", line 266, in xoscar.core.__pyx_actor_method_wrapper
  File "/home/fengyun/.local/lib/python3.8/site-packages/xorbits/_mars/services/scheduling/worker/quota.py", line 119, in request_batch_quota
    raise ValueError(
ValueError: Cannot allocate quota size 456320330460 larger than total capacity 216093589504.
```
The memory size is about 4GB when using Pandas, `456320330460` is too large.

**Comment by BlackArbsCEO** [comment]
I'm still having this problem with the newest xorbits available through pip. 
```
2023-10-02 14:15:39,732 xorbits._mars.deploy.oscar.local 25232 WARNING  Web service started at http://127.0.0.1:59977
  0%|          |   0.00/100 [00:00<?, ?it/s]2023-10-02 14:15:39,929 xorbits._mars.services.scheduling.worker.execution 25232 ERROR    Failed to run subtask eDnnloDuO0VyUkOf3tneQUCY on band numa-0
Traceback (most recent call last):
  File "C:\Users\kngka\miniconda3\envs\agd\lib\site-packages\xorbits\_mars\services\scheduling\worker\execution.py", line 494, in internal_run_subtask
    subtask_info.result = await self._retry_run_subtask(
  File "C:\Users\kngka\miniconda3\envs\agd\lib\site-packages\xorbits\_mars\services\scheduling\worker\execution.py", line 618, in _retry_run_subtask
    return await _retry_run(subtask, subtask_info, _run_subtask_once)
  File "C:\Users\kngka\miniconda3\envs\agd\lib\site-packages\xorbits\_mars\services\scheduling\worker\execution.py", line 192, in _retry_run
    raise ex
  File "C:\Users\kngka\miniconda3\envs\agd\lib\site-packages\xorbits\_mars\services\scheduling\worker\execution.py", line 154, in _retry_run
    return await target_async_func(*args)
  File "C:\Users\kngka\miniconda3\envs\agd\lib\site-packages\xorbits\_mars\services\scheduling\worker\execution.py", line 527, in _run_subtask_once
    await quota_ref.request_batch_quota(batch_quota_req)
  File "xoscar\\core.pyx", line 284, in __pyx_actor_method_wrapper
  File "xoscar\\core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
  File "C:\Users\kngka\miniconda3\envs\agd\lib\site-packages\xorbits\_mars\services\scheduling\worker\quota.py", line 119, in request_batch_quota
    raise ValueError(
ValueError: Cannot allocate quota size 19629902034.0 larger than total capacity 13668492902.
2023-10-02 14:15:39,932 xorbits._mars.services.scheduling.worker.execution 25232 ERROR    Failed to run subtask GeGwp96LjmNNdpVR6oS8x325 on band numa-0
Traceback (most recent call last):
  File "C:\Users\kngka\miniconda3\envs\agd\lib\site-packages\xorbits\_mars\services\scheduling\worker\execution.py", line 494, in internal_run_subtask
    subtask_info.result = await self._retry_run_subtask(
  File "C:\Users\kngka\miniconda3\envs\agd\lib\site-packages\xorbits\_mars\services\scheduling\worker\execution.py", line 618, in _retry_run_subtask
    return await _retry_run(subtask, subtask_info, _run_subtask_once)
  File "C:\Users\kngka\miniconda3\envs\agd\lib\site-packages\xorbits\_mars\services\scheduling\worker\execution.py", line 192, in _retry_run
    raise ex
  File "C:\Users\kngka\miniconda3\envs\agd\lib\site-packages\xorbits\_mars\services\scheduling\worker\execution.py", line 154, in _retry_run
    return await target_async_func(*args)
  File "C:\Users\kngka\miniconda3\envs\agd\lib\site-packages\xorbits\_mars\services\scheduling\worker\execution.py", line 527, in _run_subtask_once
    await quota_ref.request_batch_quota(batch_quota_req)
  File "xoscar\\core.pyx", line 284, in __pyx_actor_method_wrapper
  File "xoscar\\core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
  File "C:\Users\kngka\miniconda3\envs\agd\lib\site-packages\xorbits\_mars\services\scheduling\worker\quota.py", line 119, in request_batch_quota
    raise ValueError(
ValueError: Cannot allocate quota size 26955130596.0 larger than total capacity 13668492902.
```
