### ISSUE TITLE
BUG: Storage handler assert error on GPU

### ISSUE THREAD

**Issue by ChengjieLi28** [xprobe-inc/xorbits#378]
Note that the issue tracker is NOT the place for general support.  For
discussions about development, questions about usage, or any general questions,
contact us on https://discuss.xorbits.io/.
Q14:
```
Traceback (most recent call last):
  File "/home/lichengjie/workspace/xorbits/benchmarks/tpch/run_queries.py", line 1141, in <module>
    main()
  File "/home/lichengjie/workspace/xorbits/benchmarks/tpch/run_queries.py", line 1128, in main
    run_queries(
  File "/home/lichengjie/workspace/xorbits/benchmarks/tpch/run_queries.py", line 1058, in run_queries
    globals()[f"q{query:02}"](*queries_to_args[query])
  File "/home/lichengjie/workspace/xorbits/benchmarks/tpch/run_queries.py", line 122, in wrapped
    q(*args, **kwargs)
  File "/home/lichengjie/workspace/xorbits/benchmarks/tpch/run_queries.py", line 692, in q14
    print(total)
  File "/home/lichengjie/workspace/xorbits/python/xorbits/utils.py", line 37, in inn
    return f(self, *args, **kwargs)
  File "/home/lichengjie/workspace/xorbits/python/xorbits/core/data.py", line 261, in __str__
    run(self)
  File "/home/lichengjie/workspace/xorbits/python/xorbits/core/execution.py", line 55, in run
    mars_execute(mars_tileables, **kwargs)
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/deploy/oscar/session.py", line 1709, in execute
    return session.execute(
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/deploy/oscar/session.py", line 1526, in execute
    execution_info: ExecutionInfo = fut.result(
  File "/home/lichengjie/miniconda3/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/home/lichengjie/miniconda3/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/deploy/oscar/session.py", line 1689, in _execute
    await execution_info
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/deploy/oscar/session.py", line 102, in wait
    return await self._aio_task
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/deploy/oscar/session.py", line 848, in _run_in_background
    raise task_result.error.with_traceback(task_result.traceback)
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/services/task/supervisor/processor.py", line 388, in run
    await self._process_stage_chunk_graph(*stage_args)
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/services/task/supervisor/processor.py", line 265, in _process_stage_chunk_graph
    chunk_to_result = await self._executor.execute_subtask_graph(
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/services/task/execution/mars/executor.py", line 203, in execute_subtask_graph
    return await stage_processor.run()
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/services/task/execution/mars/stage.py", line 233, in run
    return await self._run()
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/services/task/execution/mars/stage.py", line 253, in _run
    raise self.result.error.with_traceback(self.result.traceback)
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/services/scheduling/worker/execution.py", line 393, in internal_run_subtask
    subtask_info.result = await self._retry_run_subtask(
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/services/scheduling/worker/execution.py", line 494, in _retry_run_subtask
    return await _retry_run(subtask, subtask_info, _run_subtask_once)
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/services/scheduling/worker/execution.py", line 111, in _retry_run
    raise ex
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/services/scheduling/worker/execution.py", line 73, in _retry_run
    return await target_async_func(*args)
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/services/scheduling/worker/execution.py", line 436, in _run_subtask_once
    return await asyncio.shield(aiotask)
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/services/subtask/api.py", line 70, in run_subtask_in_slot
    return await ref.run_subtask.options(profiling_context=profiling_context).send(
  File "/home/lichengjie/miniconda3/lib/python3.9/site-packages/xoscar/backends/context.py", line 204, in send
    return self._process_result_message(result)
  File "/home/lichengjie/miniconda3/lib/python3.9/site-packages/xoscar/backends/context.py", line 79, in _process_result_message
    raise message.as_instanceof_cause()
  File "/home/lichengjie/miniconda3/lib/python3.9/site-packages/xoscar/backends/pool.py", line 604, in send
    result = await self._run_coro(message.message_id, coro)
  File "/home/lichengjie/miniconda3/lib/python3.9/site-packages/xoscar/backends/pool.py", line 360, in _run_coro
    return await coro
  File "/home/lichengjie/miniconda3/lib/python3.9/site-packages/xoscar/api.py", line 123, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 524, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 516, in xoscar.core._BaseActor.__on_receive__
    return await self._handle_actor_result(result)
  File "xoscar/core.pyx", line 401, in _handle_actor_result
    task_result = await coros[0]
  File "xoscar/core.pyx", line 444, in xoscar.core._BaseActor._run_actor_async_generator
    async with self._lock:
  File "xoscar/core.pyx", line 445, in xoscar.core._BaseActor._run_actor_async_generator
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 450, in xoscar.core._BaseActor._run_actor_async_generator
    res = await gen.athrow(*res)
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/services/subtask/worker/runner.py", line 132, in run_subtask
    result = yield self._running_processor.run(subtask, self._slot_id)
  File "xoscar/core.pyx", line 455, in xoscar.core._BaseActor._run_actor_async_generator
    res = await self._handle_actor_result(res)
  File "xoscar/core.pyx", line 375, in _handle_actor_result
    result = await result
  File "/home/lichengjie/miniconda3/lib/python3.9/site-packages/xoscar/backends/context.py", line 204, in send
    return self._process_result_message(result)
  File "/home/lichengjie/miniconda3/lib/python3.9/site-packages/xoscar/backends/context.py", line 79, in _process_result_message
    raise message.as_instanceof_cause()
  File "/home/lichengjie/miniconda3/lib/python3.9/site-packages/xoscar/backends/pool.py", line 604, in send
    result = await self._run_coro(message.message_id, coro)
  File "/home/lichengjie/miniconda3/lib/python3.9/site-packages/xoscar/backends/pool.py", line 360, in _run_coro
    return await coro
  File "/home/lichengjie/miniconda3/lib/python3.9/site-packages/xoscar/api.py", line 123, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 524, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 516, in xoscar.core._BaseActor.__on_receive__
    return await self._handle_actor_result(result)
  File "xoscar/core.pyx", line 401, in _handle_actor_result
    task_result = await coros[0]
  File "xoscar/core.pyx", line 444, in xoscar.core._BaseActor._run_actor_async_generator
    async with self._lock:
  File "xoscar/core.pyx", line 445, in xoscar.core._BaseActor._run_actor_async_generator
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 450, in xoscar.core._BaseActor._run_actor_async_generator
    res = await gen.athrow(*res)
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/services/subtask/worker/processor.py", line 778, in run
    result = yield self._running_aio_task
  File "xoscar/core.pyx", line 455, in xoscar.core._BaseActor._run_actor_async_generator
    res = await self._handle_actor_result(res)
  File "xoscar/core.pyx", line 375, in _handle_actor_result
    result = await result
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/services/subtask/worker/processor.py", line 601, in run
    ) = await self._store_data(chunk_graph)
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/services/subtask/worker/processor.py", line 334, in _store_data
    store_infos = await put_infos
  File "/home/lichengjie/miniconda3/lib/python3.9/site-packages/xoscar/batch.py", line 149, in _async_batch
    return await self.batch_func(args_list, kwargs_list)
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/services/storage/api/oscar.py", line 130, in batch_put
    return await self._storage_handler_ref.put.batch(*puts)
  File "xoscar/core.pyx", line 263, in __pyx_actor_method_wrapper
    async with lock:
  File "xoscar/core.pyx", line 266, in xoscar.core.__pyx_actor_method_wrapper
    result = await result
  File "/home/lichengjie/miniconda3/lib/python3.9/site-packages/xoscar/batch.py", line 149, in _async_batch
    return await self.batch_func(args_list, kwargs_list)
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/services/storage/handler.py", line 246, in batch_put
    assert last_level == level
AssertionError: [address=127.0.0.1:38837, pid=742577]
```

**Comment by ChengjieLi28** [comment]
Q14 shows the error on storage batch ``put``.
Here's an example for showing the error on storage batch ``fetch``.
```
def test(setup_gpu):
    rs = np.random.RandomState(0)
    df = md.DataFrame(
        {
            "c": [pd.Timestamp(rs.randint(1604000000, 1604481373)) for _ in range(10)],
        },
    ).to_gpu()
    r = (df["c"] > to_datetime("2000-01-01")) & (df["c"] < to_datetime("2021-01-01"))
    print(r.execute())
```

Error:
```
ERROR    xorbits._mars.services.scheduling.worker.execution:execution.py:133 Failed to run subtask OpZI6IOXspMGEJEzlrszSQd3 on band gpu-0
Traceback (most recent call last):
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/services/scheduling/worker/execution.py", line 370, in internal_run_subtask
    await asyncio.wait_for(
  File "/home/lichengjie/miniconda3/lib/python3.9/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/services/scheduling/worker/execution.py", line 111, in _retry_run
    raise ex
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/services/scheduling/worker/execution.py", line 73, in _retry_run
    return await target_async_func(*args)
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/services/scheduling/worker/execution.py", line 213, in _prepare_input_data
    await storage_api.fetch.batch(*queries)
  File "/home/lichengjie/miniconda3/lib/python3.9/site-packages/xoscar/batch.py", line 149, in _async_batch
    return await self.batch_func(args_list, kwargs_list)
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/services/storage/api/oscar.py", line 214, in batch_fetch
    assert extracted_args == (level, band_name, dest_address, error)
AssertionError
ERROR    xorbits._mars.services.task.execution.mars.stage:stage.py:169 Subtask OpZI6IOXspMGEJEzlrszSQd3 errored
Traceback (most recent call last):
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/services/scheduling/worker/execution.py", line 370, in internal_run_subtask
    await asyncio.wait_for(
  File "/home/lichengjie/miniconda3/lib/python3.9/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/services/scheduling/worker/execution.py", line 111, in _retry_run
    raise ex
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/services/scheduling/worker/execution.py", line 73, in _retry_run
    return await target_async_func(*args)
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/services/scheduling/worker/execution.py", line 213, in _prepare_input_data
    await storage_api.fetch.batch(*queries)
  File "/home/lichengjie/miniconda3/lib/python3.9/site-packages/xoscar/batch.py", line 149, in _async_batch
    return await self.batch_func(args_list, kwargs_list)
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/services/storage/api/oscar.py", line 214, in batch_fetch
    assert extracted_args == (level, band_name, dest_address, error)
AssertionError
ERROR    xorbits._mars.services.scheduling.worker.execution:execution.py:133 Failed to run subtask Zszn0cFeJDyjGmvWOwnrt8Vf on band gpu-0
Traceback (most recent call last):
  File "/home/lichengjie/miniconda3/lib/python3.9/asyncio/tasks.py", line 466, in wait_for
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/services/scheduling/worker/execution.py", line 370, in internal_run_subtask
    await asyncio.wait_for(
  File "/home/lichengjie/miniconda3/lib/python3.9/asyncio/tasks.py", line 469, in wait_for
    return fut.result()
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/services/scheduling/worker/execution.py", line 111, in _retry_run
    raise ex
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/services/scheduling/worker/execution.py", line 73, in _retry_run
    return await target_async_func(*args)
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/services/scheduling/worker/execution.py", line 213, in _prepare_input_data
    await storage_api.fetch.batch(*queries)
  File "/home/lichengjie/miniconda3/lib/python3.9/site-packages/xoscar/batch.py", line 149, in _async_batch
    return await self.batch_func(args_list, kwargs_list)
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/services/storage/api/oscar.py", line 214, in batch_fetch
    assert extracted_args == (level, band_name, dest_address, error)
AssertionError

xorbits/_mars/dataframe/arithmetic/tests/test_arithmetic_execution.py:1011 (test_55)
setup_gpu = <function _new_test_session at 0x7fba7ff33820>

    def test_55(setup_gpu):
        rs = np.random.RandomState(0)
        df = md.DataFrame(
            {
                "c": [pd.Timestamp(rs.randint(1604000000, 1604481373)) for _ in range(10)],
            },
        ).to_gpu()
        r = (df["c"] > to_datetime("2000-01-01")) & (df["c"] < to_datetime("2021-01-01"))
>       print(r.execute())

_mars/dataframe/arithmetic/tests/test_arithmetic_execution.py:1020: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
_mars/core/entity/tileables.py:405: in execute
    result = self.data.execute(session=session, **kw)
_mars/core/entity/executable.py:152: in execute
    return execute(self, session=session, **kw)
_mars/deploy/oscar/session.py:1709: in execute
    return session.execute(
_mars/deploy/oscar/session.py:1526: in execute
    execution_info: ExecutionInfo = fut.result(
../../../../miniconda3/lib/python3.9/concurrent/futures/_base.py:446: in result
    return self.__get_result()
../../../../miniconda3/lib/python3.9/concurrent/futures/_base.py:391: in __get_result
    raise self._exception
_mars/deploy/oscar/session.py:1689: in _execute
    await execution_info
../../../../miniconda3/lib/python3.9/asyncio/tasks.py:688: in _wrap_awaitable
    return (yield from awaitable.__await__())
_mars/deploy/oscar/session.py:102: in wait
    return await self._aio_task
_mars/deploy/oscar/session.py:848: in _run_in_background
    raise task_result.error.with_traceback(task_result.traceback)
_mars/services/task/supervisor/processor.py:388: in run
    await self._process_stage_chunk_graph(*stage_args)
_mars/services/task/supervisor/processor.py:265: in _process_stage_chunk_graph
    chunk_to_result = await self._executor.execute_subtask_graph(
_mars/services/task/execution/mars/executor.py:203: in execute_subtask_graph
    return await stage_processor.run()
_mars/services/task/execution/mars/stage.py:233: in run
    return await self._run()
_mars/services/task/execution/mars/stage.py:253: in _run
    raise self.result.error.with_traceback(self.result.traceback)
_mars/services/scheduling/worker/execution.py:370: in internal_run_subtask
    await asyncio.wait_for(
../../../../miniconda3/lib/python3.9/asyncio/tasks.py:479: in wait_for
    return fut.result()
_mars/services/scheduling/worker/execution.py:111: in _retry_run
    raise ex
_mars/services/scheduling/worker/execution.py:73: in _retry_run
    return await target_async_func(*args)
_mars/services/scheduling/worker/execution.py:213: in _prepare_input_data
    await storage_api.fetch.batch(*queries)
../../../../miniconda3/lib/python3.9/site-packages/xoscar/batch.py:149: in _async_batch
    return await self.batch_func(args_list, kwargs_list)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <xorbits._mars.services.storage.api.oscar.StorageAPI object at 0x7fba1153b670>
args_list = [('c009f3b1a673128b315e756cdf1ecd4e_0',), ('fd0f861971c1890c79e1094b3076dde3_0',)]
kwargs_list = [{'band_name': 'gpu-0'}, {'band_name': 'numa-0'}]

    @fetch.batch
    async def batch_fetch(self, args_list, kwargs_list):
        extracted_args = []
        data_keys = []
        for args, kwargs in zip(args_list, kwargs_list):
            data_key, level, band_name, dest_address, error = self.fetch.bind(
                *args, **kwargs
            )
            if extracted_args:
>               assert extracted_args == (level, band_name, dest_address, error)
E               AssertionError

_mars/services/storage/api/oscar.py:214: AssertionError
```
