### ISSUE TITLE
BUG: custom aggregation func code gen doesn't work for cudf

### ISSUE THREAD

**Issue by ChengjieLi28** [xprobe-inc/xorbits#404]
Note that the issue tracker is NOT the place for general support.  For
discussions about development, questions about usage, or any general questions,
contact us on https://discuss.xorbits.io/.

TPCH SF1 Q12
```
2023-04-21 09:08:48,742 xorbits._mars.services.scheduling.worker.execution 278717 ERROR    Failed to run subtask 2APujNoJfGBmpa1VRCldJXTm on band gpu-0
Traceback (most recent call last):
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/services/subtask/worker/processor.py", line 213, in _execute_operand
    return execute(ctx, op)
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/core/operand/core.py", line 492, in execute
    result = executor(results, op)
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/core/custom_log.py", line 95, in wrap
    return func(cls, ctx, op)
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/utils.py", line 1219, in wrapped
    result = func(cls, ctx, op)
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/dataframe/groupby/aggregation.py", line 1286, in execute
    cls._execute_map(ctx, op)
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/dataframe/groupby/aggregation.py", line 1086, in _execute_map
    pre_df = func(pre_df, gpu=op.is_gpu())
  File "<string>", line 3, in expr_function
  File "/home/lichengjie/miniconda3/lib/python3.9/site-packages/cudf/core/dataframe.py", line 6890, in wrapper
    output = wrapped_func(self, other, axis, level, fill_value)
  File "/home/lichengjie/miniconda3/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/lichengjie/miniconda3/lib/python3.9/site-packages/cudf/core/indexed_frame.py", line 4229, in eq
    return self._binaryop(
  File "/home/lichengjie/miniconda3/lib/python3.9/site-packages/cudf/core/indexed_frame.py", line 2988, in _binaryop
    operands, out_index = self._make_operands_and_index_for_binop(
  File "/home/lichengjie/miniconda3/lib/python3.9/site-packages/cudf/core/dataframe.py", line 1952, in _make_operands_and_index_for_binop
    raise ValueError(
ValueError: Other is of the wrong length. Expected 2, got 8
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 100.00/100 [00:08<00:00, 11.71it/s]
Traceback (most recent call last):
  File "/home/lichengjie/workspace/xorbits/benchmarks/tpch/run_queries.py", line 1141, in <module>
    main()
  File "/home/lichengjie/workspace/xorbits/benchmarks/tpch/run_queries.py", line 1128, in main
    run_queries(
  File "/home/lichengjie/workspace/xorbits/benchmarks/tpch/run_queries.py", line 1058, in run_queries
    globals()[f"q{query:02}"](*queries_to_args[query])
  File "/home/lichengjie/workspace/xorbits/benchmarks/tpch/run_queries.py", line 122, in wrapped
    q(*args, **kwargs)
  File "/home/lichengjie/workspace/xorbits/benchmarks/tpch/run_queries.py", line 651, in q12
    print(total)
  File "/home/lichengjie/workspace/xorbits/python/xorbits/utils.py", line 37, in inn
    return f(self, *args, **kwargs)
  File "/home/lichengjie/workspace/xorbits/python/xorbits/core/data.py", line 261, in __str__
    run(self)
  File "/home/lichengjie/workspace/xorbits/python/xorbits/core/execution.py", line 55, in run
    mars_execute(mars_tileables, **kwargs)
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/deploy/oscar/session.py", line 1709, in execute
    return session.execute(
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/deploy/oscar/session.py", line 1526, in execute
    execution_info: ExecutionInfo = fut.result(
  File "/home/lichengjie/miniconda3/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/home/lichengjie/miniconda3/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/deploy/oscar/session.py", line 1689, in _execute
    await execution_info
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/deploy/oscar/session.py", line 102, in wait
    return await self._aio_task
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/deploy/oscar/session.py", line 848, in _run_in_background
    raise task_result.error.with_traceback(task_result.traceback)
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/services/task/supervisor/processor.py", line 388, in run
    await self._process_stage_chunk_graph(*stage_args)
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/services/task/supervisor/processor.py", line 265, in _process_stage_chunk_graph
    chunk_to_result = await self._executor.execute_subtask_graph(
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/services/task/execution/mars/executor.py", line 203, in execute_subtask_graph
    return await stage_processor.run()
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/services/task/execution/mars/stage.py", line 233, in run
    return await self._run()
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/services/task/execution/mars/stage.py", line 253, in _run
    raise self.result.error.with_traceback(self.result.traceback)
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/services/subtask/worker/processor.py", line 213, in _execute_operand
    return execute(ctx, op)
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/core/operand/core.py", line 492, in execute
    result = executor(results, op)
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/core/custom_log.py", line 95, in wrap
    return func(cls, ctx, op)
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/utils.py", line 1219, in wrapped
    result = func(cls, ctx, op)
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/dataframe/groupby/aggregation.py", line 1286, in execute
    cls._execute_map(ctx, op)
  File "/home/lichengjie/workspace/xorbits/python/xorbits/_mars/dataframe/groupby/aggregation.py", line 1086, in _execute_map
    pre_df = func(pre_df, gpu=op.is_gpu())
  File "<string>", line 3, in expr_function
  File "/home/lichengjie/miniconda3/lib/python3.9/site-packages/cudf/core/dataframe.py", line 6890, in wrapper
    output = wrapped_func(self, other, axis, level, fill_value)
  File "/home/lichengjie/miniconda3/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/lichengjie/miniconda3/lib/python3.9/site-packages/cudf/core/indexed_frame.py", line 4229, in eq
    return self._binaryop(
  File "/home/lichengjie/miniconda3/lib/python3.9/site-packages/cudf/core/indexed_frame.py", line 2988, in _binaryop
    operands, out_index = self._make_operands_and_index_for_binop(
  File "/home/lichengjie/miniconda3/lib/python3.9/site-packages/cudf/core/dataframe.py", line 1952, in _make_operands_and_index_for_binop
    raise ValueError(
ValueError: Other is of the wrong length. Expected 2, got 8
```

**Comment by ChengjieLi28** [comment]
take

**Comment by UranusSeven** [comment]
To reproduce:
```python
df = pd.DataFrame(
        {
            "a": rs.choice(["foo", "bar", "baz"], size=(100,)),
            "b": rs.choice(["foo", "bar", "baz"], size=(100,)),
            "c": rs.choice(["foo", "bar", "baz"], size=(100,)),
        },
        gpu=True
    )
def g1(x):
    return ((x == "foo") | (x == "bar")).sum()
df.groupby("a", as_index=False)["b"].agg(g1)
```

Error:
```python
File ~/miniconda3/envs/gpu/lib/python3.9/site-packages/cudf/core/indexed_frame.py:4229, in eq()
   4191 @_cudf_nvtx_annotate
   4192 @docutils.doc_apply(
   4193     doc_binop_template.format(
   (...)
   4227     self, other, axis="columns", level=None, fill_value=None
   4228 ):  # noqa: D102
-> 4229     return self._binaryop(
   4230         other=other, op="__eq__", fill_value=fill_value, can_reindex=True
   4231     )

File ~/miniconda3/envs/gpu/lib/python3.9/site-packages/cudf/core/indexed_frame.py:2988, in _binaryop()
   2978 def _binaryop(
   2979     self,
   2980     other: Any,
   (...)
   2985     **kwargs,
   2986 ):
   2987     reflect, op = self._check_reflected_op(op)
-> 2988     operands, out_index = self._make_operands_and_index_for_binop(
   2989         other, op, fill_value, reflect, can_reindex
   2990     )
   2991     if operands is NotImplemented:
   2992         return NotImplemented

File ~/miniconda3/envs/gpu/lib/python3.9/site-packages/cudf/core/dataframe.py:1952, in _make_operands_and_index_for_binop()
   1944     warnings.warn(
   1945         "Binary operations between host objects such as "
   1946         f"{type(other)} and cudf.DataFrame are deprecated and will be "
   (...)
   1949         FutureWarning,
   1950     )
   1951     if len(other) != self._num_columns:
-> 1952         raise ValueError(
   1953             "Other is of the wrong length. Expected "
   1954             f"{self._num_columns}, got {len(other)}"
   1955         )
   1957 lhs, rhs = self._data, other
   1958 index = self._index

ValueError: Other is of the wrong length. Expected 2, got 3
```

**Comment by UranusSeven** [comment]
Root cause: cudf doesn't support the following `eq` operation
```python
import cudf

df = cudf.DataFrame({'A': ['foo', 'bar', 'baz'], 'B': ['foo', 'foo', 'bar']})
df == 'foo'
```

You have to pass a tuple of str whose length equals the number of df's columns:
```python
df == ('foo', 'foo',)
```
