### ISSUE TITLE
BUG: user configuration not work as it cannot find the base_config.yml

### ISSUE THREAD

**Issue by luweizheng** [xprobe-inc/xorbits#456]
### Describe the bug

Users can specify custom configuration using -f option when deploying Xorbits. For example:

```
xorbits-supervisor -f my_config.yml 
```

And `my_config.yml`:

```
"@inherits": base_config.yml
storage:
  backends: [shared_memory]
oscar:
  numa:
    external_addr_scheme: ucx
```

When parsing the configuration, xorbits try to find the `base_config.yml` in the user working directory. I get the following error:

```
Traceback (most recent call last):
  File "***/envs/ucx/bin/xorbits-supervisor", line 33, in <module>
    sys.exit(load_entry_point('xorbits', 'console_scripts', 'xorbits-supervisor')())
  File "~/hpc/xorbits/python/xorbits/_mars/deploy/oscar/cmdline.py", line 220, in __call__
    self.args = self.parse_args(parser, argv)
  File "~/hpc/xorbits/python/xorbits/_mars/deploy/oscar/supervisor.py", line 47, in parse_args
    args = super().parse_args(parser, argv, environ=environ)
  File "~/hpc/xorbits/python/xorbits/_mars/deploy/oscar/cmdline.py", line 154, in parse_args
    self.config = load_service_config_file(args.config_file)
  File "~/hpc/xorbits/python/xorbits/_mars/deploy/utils.py", line 64, in load_service_config_file
    with open(path) as file:
FileNotFoundError: [Errno 2] No such file or directory: '~/hpc/test_xorbits/scripts/base_config.yml'
```
### To Reproduce
To help us to reproduce this bug, please provide the information below:

1. Python 3.9.16
2. master branch which is installed by pip install -e

### Expected behavior

Xorbits should try to find the `base_config.yml` and replaces items with user-defined configurations.

**Comment by luweizheng** [comment]
`"@inherits": @default` will fix this problem.

**Comment by qianduoduo0904** [comment]
Yeah, actually it's about doc missing. Thanks anyway.
